package com.example.math.utils

const val GAME_ONE_DURATION = 10_000L
const val ONE_SEC = 1_000L

const val PLUS = "\u002B"
const val MINUS = "\u2212"
const val DIVISION = "\u00F7"
const val MULTIPLICATION = "\u00D7"

const val TOTAL_SCORE_GAME_FOUR = "TOTAL_SCORE_GAME_FOUR"
const val TOTAL_SCORE_GAME_THREE = "TOTAL_SCORE_GAME_THREE"
const val TOTAL_SCORE_GAME_NINE = "TOTAL_SCORE_GAME_NINE"
const val TOTAL_SCORE_GAME_TEN = "TOTAL_SCORE_GAME_TEN"
const val TOTAL_SCORE_GAME_TWO = "TOTAL_SCORE_GAME_TWO"
const val TOTAL_SCORE_GAME_SIX = "TOTAL_SCORE_GAME_SIX"
const val TOTAL_SCORE_GAME_ONE = "TOTAL_SCORE_GAME_ONE"
const val BEST_SCORE_GAME_ONE = "BEST_SCORE_GAME_ONE"
const val BEST_SCORE_GAME_TWO = "BEST_SCORE_GAME_TWO"
const val BEST_SCORE_GAME_SIX = "BEST_SCORE_GAME_SIX"

const val BEST_SCORE_GAME_EIGHT = "BEST_SCORE_GAME_EIGHT"
const val BEST_SCORE_GAME_FIVE_4 = "BEST_SCORE_GAME_FIVE_4"
const val BEST_SCORE_GAME_FIVE_6 = "BEST_SCORE_GAME_FIVE_6"
const val BEST_SCORE_GAME_FIVE_8 = "BEST_SCORE_GAME_FIVE_8"


const val GAME_ONE = "GAME_ONE"
const val GAME_TWO = "GAME_TWO"
const val GAME_THREE = "GAME_THREE"
const val GAME_FOUR = "GAME_FOUR"
const val GAME_SIX = "GAME_SIX"
const val GAME_SEVEN = "GAME_SEVEN"
const val GAME_NINE = "GAME_NINE"
const val GAME_TEN = "GAME_TEN"

const val TIMER_GAME_ONE = 10
const val TIMER_GAME_TWO = 30